<?php
session_start();
$scriptList = array(
    "js/jquery-1.11.3.min.js",
    "css/initBookingForm.css",
    "css/style.css",
    "js/cookie.js",
    "js/bookRooms.js"
);
include("_php/header.php");

?>

<div id="main">

    <div id="currentBookings">
        <h2> Pending Bookings </h2>

        <ul id="bookingList">

        </ul>
    </div>

    <h2> Make a New Booking </h2>


    <!--
        Note: There are 3 stages to the booking process
        1) The #findRoomForm is shown to ask for checkin and check out dates.
           At this stage #searchingForRooms and #bookRoomForm should be hidden
        2) Once the dates have been checked, a search is made for available rooms.
           The submit button of #findRoomForm is disabled, and #searchingForRooms is shown.
        3) One the search is complete, #searchingForRooms is hidden, and #bookRoomForm is shown.
           Here the customer can select a room and finish their booking.
    -->

    <form method="post" action="validateCheckout.php" id="findRoomForm" novalidate>
        <p>
            <!-- Note: Options in the date fields could be generated by JavaScript
                 They could then also prevent invalid dates like 31-Feb being picked -->
            <label for="checkinday">Check in date:</label>
            <select name="checkinday" id="checkinday">
                    <?php
                    $count = 1;
                    $checkInDay;
                    while ($count <= 31) {
                        if ($count == $checkInDay) {
                            echo "<option selected=\"selected\" value=\"$count\">$count</option>";
                        }else {
                            echo "<option value=\"$count\">$count</option>";
                        }
                        $count ++;
                    }
                    ?>
            </select>
            <select name="checkinmonth" id="checkinmonth">
                <?php
                $values = array("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec");
                $checkinmonth;
                if (!empty($_SESSION['checkinmonth'])) {
                    $checkinmonth = $_SESSION['checkinmonth'];
                }
                foreach ($values as $cType) {
                    if ($cType == $checkinmonth) {
                        echo "<option selected=\"selected\" value=\"$cType\">$cType</option>";
                    }else {
                        echo "<option value=\"$cType\">$cType</option>";
                    }
                }
                ?>
            </select>
            <select name="checkinyear" id="checkinyear">
                <?php
                $count = 2015;
                $checkinyear;
                if (!empty($_SESSION['checkinyear'])) {
                    $checkinyear = $_SESSION['checkinyear'];
                }
                while ($count <= 2016) {
                    if ($count == $checkinyear) {
                        echo "<option selected=\"selected\" value=\"$count\">$count</option>";
                    }else {
                        echo "<option value=\"$count\">$count</option>";
                    }
                    $count ++;
                }
                ?>
            </select>
            <span id="checkinError" class="error"></span>
        </p>
        <p>
            <label for="checkout">Check out date:</label>
            <select name="checkoutday" id="checkoutday">
                <?php
                $count = 1;
                $checkoutday;
                if (!empty($_SESSION['checkoutday'])) {
                    $checkout = $_SESSION['checkoutday'];
                }
                while ($count <= 31) {
                    if ($count == $checkoutday) {
                        echo "<option selected=\"selected\" value=\"$count\">$count</option>";
                    }else {
                        echo "<option value=\"$count\">$count</option>";
                    }
                    $count ++;
                }
                ?>
            </select>
            <select name="checkoutmonth" id="checkoutmonth">
                <?php
                $values = array("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec");
                $checkoutmonth;
                if (!empty($_SESSION['checkoutmonth'])) {
                    $checkoutmonth = $_SESSION['checkoutmonth'];
                }
                foreach ($values as $cType) {
                    if ($cType == $checkoutmonth) {
                        echo "<option selected=\"selected\" value=\"$cType\">$cType</option>";
                    }else {
                        echo "<option value=\"$cType\">$cType</option>";
                    }
                }
                ?>
            </select>
            <select name="checkoutyear" id="checkoutyear">
                <?php
                $count = 2015;
                $checkoutyear;
                if (isset($_SESSION['checkoutyear'])) {
                    $checkoutyear = $_SESSION['checkoutyear'];
                }
                while ($count <= 2016) {
                    if ($count == $checkoutyear) {
                        echo "<option selected=\"selected\" value=\"$count\">$count</option>";
                    }else {
                        echo "<option value=\"$count\">$count</option>";
                    }
                    $count ++;
                }
                ?>
            </select>
            <span id="checkoutError" class="error"></span>
        </p>
        <p>
            <input type="submit" name="findRooms" id="findRooms" value="Find rooms">
        </p>
    </form>

    <div id="searchingForRooms">
        <p>Looking for rooms that are available on those dates, please wait...</p>
    </div>

    <form method="post" action="validateCheckout.php" id="bookRoomForm" novalidate>
        <input type="hidden" id="checkinDate" name="checkinDate" <?php
        // Check to see if they have already tried to validate. If so refil the form with their info.
        if (!empty($_SESSION['checkinDate'])) {
            $checkinDate = $_SESSION['checkinDate'];
            echo "value='$checkinDate'";
        } ?> >

        <input type="hidden" id="checkoutDate" name="checkoutDate" <?php
        // Check to see if they have already tried to validate. If so refil the form with their info.
        if (!empty($_SESSION['checkoutDate'])) {
            $checkoutDate = $_SESSION['checkoutDate'];
            echo "value='$checkoutDate'";
        } ?> >
        <p>
            <label for="bookingName">Guest name: </label>
            <input type="text" name="bookingName" id="bookingName"<?php
            // Check to see if they have already tried to validate. If so refil the form with their info.
            if (!empty($_SESSION['bookingName'])) {
                $bookingName = $_SESSION['bookingName'];
                echo "value='$bookingName'";
            } ?> >
            <span id="nameError" class="error"></span>
        </p>
        <p>
            <label for="roomSelection">Select a room: </label>
            <select id="roomSelection" name="roomSelection">

            </select>
        </p>
        <p>

            <input type="submit" name="bookRooms" id="bookRooms" value="Book Rooms">
        </p>
    </form>

</div>